
package com.uia.iwounder.dto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TogetherHtGoCompareWsImplService", targetNamespace = "http://ws.together.co.uk/", wsdlLocation = "https://192.168.155.18:8443/togetherTest/services/togetherHtGoCompareWs?wsdl")
public class TogetherHtGoCompareWsImplService
    extends Service
{

    private final static URL TOGETHERHTGOCOMPAREWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOGETHERHTGOCOMPAREWSIMPLSERVICE_EXCEPTION;
    private final static QName TOGETHERHTGOCOMPAREWSIMPLSERVICE_QNAME = new QName("http://ws.together.co.uk/", "TogetherHtGoCompareWsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://192.168.155.18:8443/togetherTest/services/togetherHtGoCompareWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOGETHERHTGOCOMPAREWSIMPLSERVICE_WSDL_LOCATION = url;
        TOGETHERHTGOCOMPAREWSIMPLSERVICE_EXCEPTION = e;
    }

    public TogetherHtGoCompareWsImplService() {
        super(__getWsdlLocation(), TOGETHERHTGOCOMPAREWSIMPLSERVICE_QNAME);
    }

    public TogetherHtGoCompareWsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOGETHERHTGOCOMPAREWSIMPLSERVICE_QNAME, features);
    }

    public TogetherHtGoCompareWsImplService(URL wsdlLocation) {
        super(wsdlLocation, TOGETHERHTGOCOMPAREWSIMPLSERVICE_QNAME);
    }

    public TogetherHtGoCompareWsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOGETHERHTGOCOMPAREWSIMPLSERVICE_QNAME, features);
    }

    public TogetherHtGoCompareWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TogetherHtGoCompareWsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TogetherHtWs
     */
    @WebEndpoint(name = "TogetherHtGoCompareWsImplPort")
    public TogetherHtWs getTogetherHtGoCompareWsImplPort() {
        return super.getPort(new QName("http://ws.together.co.uk/", "TogetherHtGoCompareWsImplPort"), TogetherHtWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TogetherHtWs
     */
    @WebEndpoint(name = "TogetherHtGoCompareWsImplPort")
    public TogetherHtWs getTogetherHtGoCompareWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.together.co.uk/", "TogetherHtGoCompareWsImplPort"), TogetherHtWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOGETHERHTGOCOMPAREWSIMPLSERVICE_EXCEPTION!= null) {
            throw TOGETHERHTGOCOMPAREWSIMPLSERVICE_EXCEPTION;
        }
        return TOGETHERHTGOCOMPAREWSIMPLSERVICE_WSDL_LOCATION;
    }

}
